INSERT INTO `questions` (`id`, `category`, `text`, `sort_order`, `active`) VALUES
(2, 'Verkehr & Mobilität', 'Das Velowegnetz in Volketswil muss deutlich ausgebaut und sicherer gestaltet werden', 2, 1),
(3, 'Verkehr & Mobilität', 'Volketswil braucht mehr und bessere ÖV-Verbindungen mit höheren Taktfrequenzen', 3, 1),
(4, 'Verkehr & Mobilität', 'Die Gemeinde soll Parkplätze im Zentrum reduzieren zugunsten von Grünflächen und Aufenthaltsqualität', 4, 1),
(5, 'Verkehr & Mobilität', 'Volketswil braucht mehr sichere Fusswege und barrierefreie Übergänge', 5, 1),
(6, 'Verkehr & Mobilität', 'Die Gemeinde soll Auto-Teilen fördern oder einführen', 6, 1),
(7, 'Verkehr & Mobilität', 'Am Bahnhof Schwerzenbach braucht es mehr überdachte und sichere Veloabstellplätze', 7, 1),
(9, 'Verkehr & Mobilität', 'Die Gemeinde muss durchgehende Velorouten schaffen, auf denen Velofahrende Vortritt haben', 9, 1),
(10, 'Wohnen & Siedlungsentwicklung', 'Volketswil muss aktiv bezahlbaren Wohnraum für Familien und Menschen mit tiefem Einkommen schaffen', 10, 1),
(11, 'Wohnen & Siedlungsentwicklung', 'Die Gemeinde soll beim Verdichten den Erhalt von Grünräumen und Bäumen priorisieren', 11, 1),
(12, 'Wohnen & Siedlungsentwicklung', 'Volketswil braucht mehr gemeinnützigen Wohnungsbau (z.B. Genossenschaften)', 12, 1),
(13, 'Wohnen & Siedlungsentwicklung', 'Die Gemeinde soll Mindeststandards für umweltfreundliches Bauen verbindlich vorschreiben', 13, 1),
(14, 'Wohnen & Siedlungsentwicklung', 'Volketswil muss verhindern, dass zu viele Böden versiegelt werden und soll Grünflächen bei Neubauten vorschreiben', 14, 1),
(15, 'Wohnen & Siedlungsentwicklung', 'Die Gemeinde soll aktiv in eigene Wohnungen investieren', 15, 1),
(16, 'Wohnen & Siedlungsentwicklung', 'Volketswil braucht eine durchmischte Quartierstruktur', 16, 1),
(17, 'Wohnen & Siedlungsentwicklung', 'Die Gemeinde soll das Ortsbild schützen und gegen gesichtslose Überbauungen vorgehen', 17, 1),
(18, 'Bildung & Kinderbetreuung', 'Volketswil braucht mehr günstiger Krippenplätze für alle Einkommensschichten', 18, 1),
(19, 'Bildung & Kinderbetreuung', 'Die Gemeinde soll flächendeckende Tagesstrukturen mit Betreuung über Mittag anbieten', 19, 1),
(20, 'Bildung & Kinderbetreuung', 'Volketswil muss mehr in die Schulsozialarbeit und psychosoziale Unterstützung investieren', 20, 1),
(21, 'Bildung & Kinderbetreuung', 'Die Gemeinde soll alle Schulwege konsequent sicherer machen', 21, 1),
(22, 'Bildung & Kinderbetreuung', 'Volketswil braucht mehr naturnahe Spiel- und Freiräume für Kinder', 22, 1),
(23, 'Bildung & Kinderbetreuung', 'Die Gemeinde soll ein Ferienbetreuungsangebot schaffen', 23, 1),
(24, 'Bildung & Kinderbetreuung', 'Volketswil muss Bildungsangebote unabhängig vom Einkommen der Eltern zugänglich machen', 24, 1),
(25, 'Bildung & Kinderbetreuung', 'Die Gemeinde soll mehr in Jugendarbeit und niederschwellige Angebote für Jugendliche investieren', 25, 1),
(26, 'Wirtschaft & Arbeit', 'Volketswil soll lokale, nachhaltige Betriebe gezielt fördern', 26, 1),
(27, 'Wirtschaft & Arbeit', 'Die Gemeinde muss Kriterien für Umweltschutz und faire Arbeitsbedingungen bei der Ansiedlung von Unternehmen einführen', 27, 1),
(28, 'Wirtschaft & Arbeit', 'Volketswil braucht mehr Verkaufsläden mit regionalem und biologischem Sortiment', 28, 1),
(29, 'Wirtschaft & Arbeit', 'Die Gemeinde soll leerstehende Ladenlokale für soziale oder kulturelle Zwecke nutzen', 29, 1),
(30, 'Wirtschaft & Arbeit', 'Volketswil muss bei der öffentlichen Beschaffung konsequent auf faire und umweltfreundliche Produkte setzen', 30, 1),
(31, 'Wirtschaft & Arbeit', 'Die Gemeinde soll aktiv Arbeitsintegrationsprojekte unterstützen', 31, 1),
(32, 'Wirtschaft & Arbeit', 'Volketswil soll bei der Standortförderung Lebensqualität gleichwertig zur Wirtschaftsförderung behandeln', 32, 1),
(34, 'Wirtschaft & Arbeit', 'Volketswil braucht mehr Gewerbe und Dienstleistungen für lokale Arbeitsplätze statt nur Grossunternehmen', 34, 1),
(35, 'Wirtschaft & Arbeit', 'Die Gemeinde soll gemeinschaftliche Arbeitsräume fördern um Pendelverkehr zu reduzieren', 35, 1),
(37, 'Natur, Umwelt & Energie', 'Die Gemeinde soll eine Solarpflicht für Neubauten und Sanierungen einführen', 37, 1),
(38, 'Natur, Umwelt & Energie', 'Volketswil braucht mehr Naturschutzflächen und verbundene Grünräume für Tiere und Pflanzen', 38, 1),
(39, 'Natur, Umwelt & Energie', 'Die Gemeinde muss öffentliche Grünflächen naturnah und ohne Pflanzenschutzmittel bewirtschaften', 39, 1),
(40, 'Natur, Umwelt & Energie', 'Volketswil soll ein Förderprogramm für private Solaranlagen und energetische Sanierungen auflegen', 40, 1),
(41, 'Natur, Umwelt & Energie', 'Die Gemeinde muss mehr Bäume pflanzen und bestehenden Baumbestand konsequent schützen', 41, 1),
(42, 'Natur, Umwelt & Energie', 'Volketswil braucht eine Klimastrategie mit verbindlichen Zielen und Massnahmen', 42, 1),
(43, 'Natur, Umwelt & Energie', 'Die Gemeinde soll Lebensmittelverschwendung aktiv bekämpfen und Lebensmittelabgabe fördern', 43, 1),
(44, 'Natur, Umwelt & Energie', 'Volketswil muss die Versiegelung von Flächen stoppen und Entsiegelungsprojekte fördern', 44, 1),
(45, 'Natur, Umwelt & Energie', 'Die Gemeinde soll mehr öffentliche Trinkbrunnen installieren', 45, 1),
(46, 'Infrastruktur & Versorgung', 'Volketswil muss in die Sanierung und Erneuerung der Infrastruktur investieren statt zu sparen', 46, 1),
(47, 'Infrastruktur & Versorgung', 'Die Gemeinde soll öffentliche Gebäude energetisch sanieren und klimaneutral betreiben', 47, 1),
(48, 'Infrastruktur & Versorgung', 'Volketswil braucht mehr öffentliche Toiletten auch ausserhalb des Zentrums', 48, 1),
(49, 'Infrastruktur & Versorgung', 'Die Gemeinde muss Zugänge ohne Hindernisse zu allen öffentlichen Einrichtungen sicherstellen', 49, 1),
(50, 'Gesundheit & Soziales', 'Volketswil braucht mehr einfach zugängliche Beratungsangebote für Menschen in schwierigen Lebenslagen', 50, 1),
(51, 'Gesundheit & Soziales', 'Die Gemeinde soll aktiv gegen Altersarmut vorgehen und Unterstützungsangebote ausbauen', 51, 1),
(52, 'Gesundheit & Soziales', 'Volketswil muss mehr in die Integration von Zugewanderten und Sprachförderung investieren', 52, 1),
(53, 'Gesundheit & Soziales', 'Die Gemeinde soll kostenlose Begegnungsorte für alle Altersgruppen schaffen', 53, 1),
(55, 'Gesundheit & Soziales', 'Die Gemeinde muss die Spitex-Versorgung sicherstellen und unterstützen', 55, 1),
(56, 'Gesundheit & Soziales', 'Volketswil soll aufsuchende Sozialarbeit einführen für Menschen die keine Hilfe suchen', 56, 1),
(57, 'Gesundheit & Soziales', 'Die Gemeinde braucht kleinere, bezahlbare Alterswohnungen in allen Ortsteilen nicht nur zentral', 57, 1),
(58, 'Kultur, Freizeit & Sport', 'Volketswil braucht mehr öffentliche Räume für kulturelle und soziale Aktivitäten', 58, 1),
(59, 'Kultur, Freizeit & Sport', 'Die Gemeinde soll Sportangebote für alle Einkommensschichten zugänglich machen', 59, 1),
(60, 'Kultur, Freizeit & Sport', 'Volketswil muss mehr in Treffpunkte für Jugendliche investieren', 60, 1),
(61, 'Kultur, Freizeit & Sport', 'Die Gemeinde soll lokale Kulturschaffende und Vereine stärker finanziell unterstützen', 61, 1),
(62, 'Kultur, Freizeit & Sport', 'Volketswil braucht mehr Begegnungszonen im öffentlichen Raum', 62, 1),
(63, 'Kultur, Freizeit & Sport', 'Die Gemeinde muss öffentliche Plätze einladender und lebendiger gestalten', 63, 1),
(65, 'Kultur, Freizeit & Sport', 'Volketswil muss mehr in lokale Kultur- und Freizeitinfrastruktur investieren um keine Schlafstadt zu werden', 65, 1),
(66, 'Kultur, Freizeit & Sport', 'Die Gemeinde soll das lokale Engagement der Bevölkerung durch bessere Infrastruktur fördern', 66, 1),
(67, 'Kultur, Freizeit & Sport', 'Die Gemeinde soll Kulturförderung auf lokaler Ebene verstärken', 67, 1),
(68, 'Sicherheit', 'Volketswil braucht mehr Prävention und Jugendarbeit', 68, 1),
(69, 'Sicherheit', 'Die Gemeinde soll in die Beleuchtung von Fuss- und Velowegen investieren für mehr Sicherheitsgefühl', 69, 1),
(70, 'Sicherheit', 'Volketswil muss Littering mit Mehrwegsystemen und mehr Abfalleimern bekämpfen', 70, 1),
(71, 'Finanzen & Steuern', 'Volketswil soll soziale und umweltfreundliche Investitionen priorisieren statt Steuern zu senken', 71, 1),
(72, 'Finanzen & Steuern', 'Die Gemeinde muss bei Sparmassnahmen soziale Leistungen und Bildung verschonen', 72, 1),
(73, 'Finanzen & Steuern', 'Volketswil braucht eine Gebührenordnung, die einkommensschwache Haushalte entlastet', 73, 1),
(74, 'Politik & Verwaltung', 'Volketswil muss mehr Möglichkeiten zur Mitbestimmung für die Bevölkerung schaffen', 74, 1),
(75, 'Politik & Verwaltung', 'Die Gemeinde soll wichtige Entscheide mit breiten Mitwirkungsverfahren vorbereiten', 75, 1),
(76, 'Politik & Verwaltung', 'Volketswil braucht mehr Transparenz über politische Entscheidungsprozesse', 76, 1),
(77, 'Politik & Verwaltung', 'Die Gemeinde muss Informationen auch in einfacher Sprache und mehrsprachig bereitstellen', 77, 1),
(78, 'Politik & Verwaltung', 'Volketswil soll Jugendliche aktiv in politische Prozesse einbeziehen', 78, 1),
(79, 'Generationenthemen', 'Volketswil braucht mehr Wohn- und Begegnungsprojekte, die verschiedene Generationen zusammenbringen', 79, 1),
(80, 'Generationenthemen', 'Die Gemeinde muss Spielplätze und Aufenthaltsorte für verschiedene Altersgruppen gemeinsam planen', 80, 1),
(81, 'Generationenthemen', 'Volketswil soll Programme zur Bekämpfung von Einsamkeit im Alter auflegen', 81, 1),
(82, 'Landwirtschaft & Landschaft', 'Volketswil muss landwirtschaftliche Flächen vor Überbauung schützen', 82, 1),
(83, 'Landwirtschaft & Landschaft', 'Die Gemeinde soll biologische und regionale Landwirtschaft aktiv fördern', 83, 1),
(84, 'Landwirtschaft & Landschaft', 'Volketswil braucht mehr öffentlich zugängliche Naherholungsgebiete', 84, 1),
(85, 'Landwirtschaft & Landschaft', 'Die Gemeinde soll lokale Lebensmittel in öffentlichen Einrichtungen einsetzen', 85, 1),
(86, 'Landwirtschaft & Landschaft', 'Volketswil muss Direktvermarktung und Hofläden unterstützen', 86, 1),
(87, 'Digitalisierung & Innovation', 'Volketswil soll sicherstellen, dass alle Generationen digitale Angebote nutzen können - mit Unterstützung', 87, 1),
(88, 'Digitalisierung & Innovation', 'Die Gemeinde muss bei der Digitalisierung Datenschutz und Barrierefreiheit prioritär behandeln', 88, 1),
(89, 'Digitalisierung & Innovation', 'Volketswil braucht weiterhin persönliche Beratung auf der Gemeinde trotz Digitalisierung', 89, 1),
(90, 'Digitalisierung & Innovation', 'Volketswil muss digitale Unabhängigkeit sicherstellen und nicht von einzelnen Anbietern abhängig werden', 90, 1),
(91, 'Digitalisierung & Innovation', 'Die Gemeinde soll den Einsatz von KI in der Verwaltung transparent und ethisch gestalten', 91, 1),
(92, 'Demokratie & Mitbestimmung', 'Volketswil braucht ein Parlament zur besseren demokratischen Vertretung bei fast 20000 Einwohnenden', 92, 1),
(93, 'Demokratie & Mitbestimmung', 'Die Gemeinde muss Menschen ohne Stimmrecht (Ausländer*innen, Jugendliche) stärker in Entscheidungsprozesse einbeziehen', 93, 1),
(96, 'Strategische Entwicklung & Planung', 'Die Gemeinde muss auf den Übergang zur Stadt mit über 20000 Einwohnenden vorbereitet sein', 96, 1),
(97, 'Strategische Entwicklung & Planung', 'Volketswil soll faktenbasierte Entscheidungen statt Bauchgefühl zur Grundlage machen', 97, 1),
(98, 'Strategische Entwicklung & Planung', 'Die Gemeinde braucht ein Gesamtkonzept das Wirtschaft, Wohnen und soziale Infrastruktur verbindet', 95, 1),
(99, 'Zentrum & Ortsteile', 'Volketswil braucht einen attraktiven lebendigen Kern mit gleichzeitigem Erhalt der ländlichen Dorfteile', 99, 1),
(100, 'Zentrum & Ortsteile', 'Die Gemeinde muss das Zentrum rund um das Gemeindehaus als lebendigen Begegnungsort gestalten', 100, 1),
(101, 'Zentrum & Ortsteile', 'Volketswil soll in allen Ortsteilen attraktive Begegnungsorte schaffen nicht nur im Zentrum', 101, 1),
(102, 'Zentrum & Ortsteile', 'Die Gemeinde braucht mehr Gastronomie und Aufenthaltsqualität im öffentlichen Raum', 102, 1),
(103, 'Regionale Zusammenarbeit', 'Volketswil muss bei Verkehr, Raumplanung und Infrastruktur gemeinsame Lösungen mit Nachbargemeinden suchen', 103, 1),
(104, 'Regionale Zusammenarbeit', 'Die Gemeinde soll aktiv Bundesmittel für regionale Projekte akquirieren', 104, 1),
(105, 'Regionale Zusammenarbeit', 'Volketswil soll die Chancen des Innovationsparks nutzen und allfällige Nachteile reduzieren', 105, 1),
(106, 'Quartierentwicklung', 'Volketswil soll in wachsenden Ortsteilen professionelle Quartierarbeit etablieren', 106, 1),
(107, 'Quartierentwicklung', 'Die Gemeinde braucht soziokulturelle Angebote auch ausserhalb des Zentrums', 107, 1),
(109, 'Verkehr & Mobilität', 'Volketswil braucht mehr Tempo-30-Zonen zum Schutz von Kindern und Anwohnenden', 0, 1);